### ISSUE TITLE
Order of checking locations 

### ISSUE THREAD

**Issue by ahilles107** [liip/LiipThemeBundle#147]
Hey, i have question:

Why we check there first files from regular views files and themes only as fallback? It shouldn't be opposite? We first look in themes and if file not exist we fallback to project views?  

code: https://github.com/liip/LiipThemeBundle/blob/master/Twig/Loader/FilesystemLoader.php#L68

**Comment by grigoryosifov** [comment]
I am just struggling with the same logic.

**Comment by grigoryosifov** [comment]
@ahilles107 just found the solution.
If you are using templates only on global application level, you have to enter their full namespaced paths, e.g.:

```
// src/AppBundle/Controller/DefaultController.php
...
        return $this->render(':default:index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.root_dir').'/..'),
        ]);
...
```
instead of just:

```
// app/Resources/themes/mytheme/default/index.html.twig
...
        return $this->render('default:index.html.twig', [
            'base_dir' => realpath($this->getParameter('kernel.root_dir').'/..'),
        ]);
...```

and of course for the extended templates as well:

```
// app/Resources/themes/mytheme/default/index.html.twig
{% extends '::base.html.twig' %}
```
instead of just:

```
// app/Resources/themes/mytheme/default/index.html.twig
{% extends 'base.html.twig' %}
```
The issue is that they are provided somehow shortened in the Symfony standard framework and from there comes the confusion.
