### ISSUE TITLE
Problems overriding twig file systemloader (twig 2.0)

### ISSUE THREAD

**Issue by elonmir** [liip/LiipThemeBundle#161]
I just had the issue, that I had twig 2.0 in my vendors (still have to figure out why), and tried to install the theme bundle.

That resulted in following warning:

> PHP Warning:  Declaration of Liip\ThemeBundle\Twig\Loader\FilesystemLoader::findTemplate($template) should be compatible with Twig_Loader_Filesystem::findTemplate($name, $throw = true) in /srv/www/bestfewo.de/vendor/liip/theme-bundle/Twig/Loader/FilesystemLoader.php on line 10

Turns out the filesystem loader has a second parameter in twig 2.0, but isn't implemented in the overriding class.

**Comment by xabbuh** [comment]
> I just had the issue, that I had twig 2.0 in my vendors (still have to figure out why) [...]

Symfony does work with Twig 1.x and 2.x. Thus, it does not have version constraints excluding any of these versions. However, due to the `minimum-stability` settings in your `composer.json` file being set to `stable` (which is the default in the Symfony Standard Edition) you would never have end up with Twig 2.x when running `composer update` until a few days ago when Twig 2.0 was released. Now Composer will install stable releases of Twig 2.x if you do not explicitly depend on Twig 1.x.

I have opened #162 to make the `FilesystemLoader` compatible with Twig 2.x. Could you please check if the suggested patch solves your issue?

**Comment by elonmir** [comment]
Thanks for the insight, I already suspected something in that direction, but wasn't able to confirm my suspicion.

The patch seems to solve the issue, thank you very much.
