### ISSUE TITLE
Can't work overriding for symfony 4.3 templates/bundles

### ISSUE THREAD

**Issue by Pasuvan** [liip/LiipThemeBundle#201]
Hi, already I put the question for Symfony portal, Please can you check that below link
https://github.com/symfony/symfony/issues/33845

**Comment by dpmR** [comment]
I am facing the same problem. After digging into the code I think I found the root of the problem.

https://github.com/liip/LiipThemeBundle/blob/362394821ff8dcc90b06272e289e7dafe4dab52a/Locator/FileLocator.php#L134
=> $name contains 'views/@BundleName' instead of '@Bundle' so it does not jump into locateBundleResource

Also in https://github.com/liip/LiipThemeBundle/blob/362394821ff8dcc90b06272e289e7dafe4dab52a/Locator/FileLocator.php#L167 the 'views/' part needs to be removed.

**Comment by Pasuvan** [comment]
Thanks @dpmR it's worked
